### ISSUE TITLE
[Feature] Data Access Classes

### ISSUE THREAD

**Issue by lucasprates74** [CSC207-2022F-UofT/course-project-team-bbq#13]

**Comment by ThomasShimUoft** [comment]
I think for saveFlashcardID, we can either delete this method and use saveFlashcardSet to do both because in this case, the implementation would be the exact same, and we do not want duplicate code or we can change the method signature for this method to only receive the necessary ids and create a new FlashcardSetDSRequestModel and change the flashcards instance variable. 

We talked about using the necessary ids but thinking back, I think we need to use a DSRequestModel to follow clean architecture. I think we cannot directly call a method in FlashcardSetDataAccess in the use case layer.

**Comment by Edward-1117** [comment]
Currently, this is how my interactor is accessing the database to store flashcard sets:

FlashcardSetInteractor --> IFlashcardSetDataAccess<Interface> --> FlashcardSetDataAccess (implements IFlashcardSetDataAccess) --> FlashcardSet.csv<Database>

This is consistent with Clean Architecture, right?

**Comment by ThomasShimUoft** [comment]
Yes this is consistent with Clean Architecture. My data flow is as following:

FlashcardSetInteractor --> DBGateway --> IFlashcardSetDataAccess(via DBGateway) --> FlashcardSetDataAccess(implements IFlashcardSetDataACcess) --> FlashcardSet.csv

Should we have everyone use DBGateway for the purpose of consistency or just continue with what we have?

**Comment by ThomasShimUoft** [comment]
> I think for saveFlashcardID, we can either delete this method and use saveFlashcardSet to do both because in this case, the implementation would be the exact same, and we do not want duplicate code or we can change the method signature for this method to only receive the necessary ids and create a new FlashcardSetDSRequestModel and change the flashcards instance variable.
> 
> We talked about using the necessary ids but thinking back, I think we need to use a DSRequestModel to follow clean architecture. I think we cannot directly call a method in FlashcardSetDataAccess in the use case layer.

Nevermind, I think we can continue. Looking back on the clean architecture diagram, as long as our data access classes implement the corresponding data access interfaces, the use case layer can call any method with any parameters.
