### ISSUE TITLE
[Feature] Deleting a Flashcard Set

### ISSUE THREAD

**Issue by Edward-1117** [CSC207-2022F-UofT/course-project-team-bbq#29]
Allow users to delete a flashcard set with a specified id.

**Comment by ThomasShimUoft** [comment]
When deleting a flashcardSet will we have to delete all the corresponding flashcards from the database?

I think we will have to because all flashcards even duplicate ones will have different ids.
So in this case it might be better to consider having DBGateway instead of separate IFlashcardSetDataAccess and IFlashcardDataAccess.

**Comment by Edward-1117** [comment]
Hmm, from the user's perspective I think a user might want to delete a set, but still keep all the individual flashcards for later when creating another set. So, if I delete a particular flashcard set in FlashcardSets.csv, all the associated flashcards within that set would persist in Flashcards.csv?

**Comment by ThomasShimUoft** [comment]
However, the user can only have flashcards when they are in a flashcard set. So if we delete a flashcard set, the user will not have any way to access the flashcards in that deleted set. We also have it so that every flashcard whether duplicate in two separate flashcardSets have different ids, so if they want a flashcard in another set, they would have to make a new one.
